[package]
name = "rhs_mailer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"]}
serde = { version = "1.0.132", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
lettre = "0.10.0-rc.4"
dotenv = "0.15.0"
